#!/bin/bash

# comments start with a '#" -n 3 -m 0.2

cd Downloads
chef -n 50 -m 0.2
./saladmaker -t1 2.1 -t2 2.4 -s 32769 -y n
./saladmaker -t1 2.1 -t2 2.4 -s 32769 -y p
./saladmaker -t1 0.2 -t2 0.4 -s 819203 -y k